#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Automate multivariate data visualizations
Created on Tue Jul 24 12:31:16 2018

@author: mm82089
"""

import matplotlib.pyplot as plt
plt.style.use('classic')
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sns

import base64
from distutils.version import LooseVersion
import pandas_profiling.base as base
import matplotlib

# Create some data
rng = np.random.RandomState(0)
x = np.linspace(0, 10, 500)
y = np.cumsum(rng.randn(500, 6), 0)

# Plot the data with Matplotlib defaults
plt.plot(x, y)
plt.legend('ABCDEF', ncol=2, loc='upper left');